-- 코드를 입력하세요
SELECT b.BOOK_ID, a.AUTHOR_NAME, date_format(b.PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK b, AUTHOR a
WHERE b.AUTHOR_ID = a.AUTHOR_ID AND CATEGORY = "경제"
ORDER BY PUBLISHED_DATE ASC;