-- 코드를 입력하세요
SELECT distinct B.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "세단" and START_DATE LIKE "%-10-%"
ORDER BY CAR_ID DESC